# Numpy Solutions

In [4]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [5]:

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.shape)

(3,)


In [7]:
arr[1]=9
print(arr)

[1 9 3]


In [8]:
arr2=np.array([[1,2,3],[4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
arr2[1][-2]

5

In [10]:
arr_str = np.array(['sanjeev', 'Raja', 'Tuhin', 'Amar'])
print(arr_str)

['sanjeev' 'Raja' 'Tuhin' 'Amar']


In [11]:
arr_int = np.arange(0,60,3)
print(arr_int)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]


In [12]:
aar = np.linspace(0,10,5)
print(aar)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
aar = np.random.rand(3, 3)
aar

array([[0.05999835, 0.51096991, 0.5661098 ],
       [0.0473314 , 0.30772075, 0.15999738],
       [0.33528922, 0.83931418, 0.01779547]])

In [14]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(np.ones((5, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
arr = [1,2,3]
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [17]:
print(np.tile(arr,3))

[1 2 3 1 2 3 1 2 3]


In [18]:
id_mat = np.eye(3)
id_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [20]:
np.diag(arr)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
aar.ndim

2

In [22]:
aar.size

9

In [23]:
aar.shape

(3, 3)

In [24]:
np.random.randint(-10, 10, 4)

array([ 4, -4,  2,  2])

In [25]:
np.exp(aar)

array([[1.0618348 , 1.66690717, 1.76140151],
       [1.04846942, 1.36032106, 1.1735078 ],
       [1.39834476, 2.31477892, 1.01795475]])

In [26]:
np.log10(aar)

array([[-1.22186069, -0.29160467, -0.24709932],
       [-1.32485063, -0.51184322, -0.79588712],
       [-0.4745804 , -0.07607544, -1.7496906 ]])

In [27]:
np.sum(aar)

2.8445264714474314

In [28]:
np.min(aar, axis=1)

array([0.05999835, 0.0473314 , 0.01779547])

In [29]:
np.mean(aar)

0.3160584968274924

In [30]:
np.median(aar)

0.3077207450107652

In [31]:
np.var(aar)

0.06953876930841968

In [32]:
aar[1:, 2:-1]

array([], shape=(2, 0), dtype=float64)

In [33]:
np.sort(aar, axis=0)

array([[0.0473314 , 0.30772075, 0.01779547],
       [0.05999835, 0.51096991, 0.15999738],
       [0.33528922, 0.83931418, 0.5661098 ]])

In [34]:
ar =np.array([[1,8,9],[3,0,7],[2,5,8],[7,4,3]])
ar

array([[1, 8, 9],
       [3, 0, 7],
       [2, 5, 8],
       [7, 4, 3]])

# Transpose

In [35]:
ar[:3, :].T

array([[1, 3, 2],
       [8, 0, 5],
       [9, 7, 8]])

In [36]:
np.append(arr_str, 'kumar')

array(['sanjeev', 'Raja', 'Tuhin', 'Amar', 'kumar'], dtype='<U7')

In [37]:
np.insert(arr_str, 1,['pawan','aarbh'])

array(['sanjeev', 'pawan', 'aarbh', 'Raja', 'Tuhin', 'Amar'], dtype='<U7')

In [42]:
arr_str

array(['sanjeev', 'Raja', 'Tuhin', 'Amar'], dtype='<U7')

In [46]:
s1 = np.array([[1,2,3],[2,3,4]])
s2 = np.array([[4,5,6],[9,6,3]])
arr_cat = np.concatenate((s1,s2), axis=0)
print(arr_cat)

[[1 2 3]
 [2 3 4]
 [4 5 6]
 [9 6 3]]


In [47]:
cat = np.hstack((s1,s2))
cat

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 9, 6, 3]])

In [52]:
arr = np.array([1, 2, 3, 2, 3, 1, 5, 6,3])
np.unique(arr)

array([1, 2, 3, 5, 6])

In [53]:
uniques,counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 5 6]
[2 2 3 1 1]


In [56]:
arr1 = np.array([1, 2, 3, 4, 6])
arr2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(arr1, arr2))
print(np.union1d(arr1, arr2))
print(np.setdiff1d(arr1, arr2))
print(np.setxor1d(arr1, arr2))

[3 4 6]
[1 2 3 4 5 6 7]
[1 2]
[1 2 5 7]
